//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace SeLogerExtractor.DataAccess.DataAccess
{
    #region Contextes
    
    /// <summary>
    /// Aucune documentation sur les métadonnées n'est disponible.
    /// </summary>
    public partial class ModelSeLogerContainer : ObjectContext
    {
        #region Constructeurs
    
        /// <summary>
        /// Initialise un nouvel objet ModelSeLogerContainer à l'aide de la chaîne de connexion trouvée dans la section 'ModelSeLogerContainer' du fichier de configuration d'application.
        /// </summary>
        public ModelSeLogerContainer() : base("name=ModelSeLogerContainer", "ModelSeLogerContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialisez un nouvel objet ModelSeLogerContainer.
        /// </summary>
        public ModelSeLogerContainer(string connectionString) : base(connectionString, "ModelSeLogerContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialisez un nouvel objet ModelSeLogerContainer.
        /// </summary>
        public ModelSeLogerContainer(EntityConnection connection) : base(connection, "ModelSeLogerContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Méthodes partielles
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Propriétés ObjectSet
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        public ObjectSet<Annonce> Annonce
        {
            get
            {
                if ((_Annonce == null))
                {
                    _Annonce = base.CreateObjectSet<Annonce>("Annonce");
                }
                return _Annonce;
            }
        }
        private ObjectSet<Annonce> _Annonce;

        #endregion

        #region Méthodes AddTo
    
        /// <summary>
        /// Méthode déconseillée pour ajouter un nouvel objet à l'EntitySet Annonce. Utilisez la méthode .Add de la propriété ObjectSet&lt;T&gt; associée à la place.
        /// </summary>
        public void AddToAnnonce(Annonce annonce)
        {
            base.AddObject("Annonce", annonce);
        }

        #endregion

    }

    #endregion

    #region Entités
    
    /// <summary>
    /// Aucune documentation sur les métadonnées n'est disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ModelSeLoger", Name="Annonce")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Annonce : EntityObject
    {
        #region Méthode de fabrique
    
        /// <summary>
        /// Créez un nouvel objet Annonce.
        /// </summary>
        /// <param name="id">Valeur initiale de la propriété Id.</param>
        /// <param name="piscine">Valeur initiale de la propriété Piscine.</param>
        /// <param name="terasse">Valeur initiale de la propriété Terasse.</param>
        /// <param name="dateStart">Valeur initiale de la propriété DateStart.</param>
        /// <param name="dateUpdate">Valeur initiale de la propriété DateUpdate.</param>
        /// <param name="version">Valeur initiale de la propriété Version.</param>
        /// <param name="isCurrentVersion">Valeur initiale de la propriété IsCurrentVersion.</param>
        /// <param name="dPE">Valeur initiale de la propriété DPE.</param>
        /// <param name="gES">Valeur initiale de la propriété GES.</param>
        public static Annonce CreateAnnonce(global::System.Int32 id, global::System.Boolean piscine, global::System.Boolean terasse, global::System.DateTime dateStart, global::System.DateTime dateUpdate, global::System.Int32 version, global::System.Boolean isCurrentVersion, global::System.String dPE, global::System.String gES)
        {
            Annonce annonce = new Annonce();
            annonce.Id = id;
            annonce.Piscine = piscine;
            annonce.Terasse = terasse;
            annonce.DateStart = dateStart;
            annonce.DateUpdate = dateUpdate;
            annonce.Version = version;
            annonce.IsCurrentVersion = isCurrentVersion;
            annonce.DPE = dPE;
            annonce.GES = gES;
            return annonce;
        }

        #endregion

        #region Propriétés primitives
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Title
        {
            get
            {
                return _Title;
            }
            set
            {
                OnTitleChanging(value);
                ReportPropertyChanging("Title");
                _Title = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Title");
                OnTitleChanged();
            }
        }
        private global::System.String _Title;
        partial void OnTitleChanging(global::System.String value);
        partial void OnTitleChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Village
        {
            get
            {
                return _Village;
            }
            set
            {
                OnVillageChanging(value);
                ReportPropertyChanging("Village");
                _Village = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Village");
                OnVillageChanged();
            }
        }
        private global::System.String _Village;
        partial void OnVillageChanging(global::System.String value);
        partial void OnVillageChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> Price
        {
            get
            {
                return _Price;
            }
            set
            {
                OnPriceChanging(value);
                ReportPropertyChanging("Price");
                _Price = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Price");
                OnPriceChanged();
            }
        }
        private Nullable<global::System.Double> _Price;
        partial void OnPriceChanging(Nullable<global::System.Double> value);
        partial void OnPriceChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ConstuctionYear
        {
            get
            {
                return _ConstuctionYear;
            }
            set
            {
                OnConstuctionYearChanging(value);
                ReportPropertyChanging("ConstuctionYear");
                _ConstuctionYear = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ConstuctionYear");
                OnConstuctionYearChanged();
            }
        }
        private Nullable<global::System.Int32> _ConstuctionYear;
        partial void OnConstuctionYearChanging(Nullable<global::System.Int32> value);
        partial void OnConstuctionYearChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> Surface
        {
            get
            {
                return _Surface;
            }
            set
            {
                OnSurfaceChanging(value);
                ReportPropertyChanging("Surface");
                _Surface = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Surface");
                OnSurfaceChanged();
            }
        }
        private Nullable<global::System.Double> _Surface;
        partial void OnSurfaceChanging(Nullable<global::System.Double> value);
        partial void OnSurfaceChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> Terrain
        {
            get
            {
                return _Terrain;
            }
            set
            {
                OnTerrainChanging(value);
                ReportPropertyChanging("Terrain");
                _Terrain = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Terrain");
                OnTerrainChanged();
            }
        }
        private Nullable<global::System.Double> _Terrain;
        partial void OnTerrainChanging(Nullable<global::System.Double> value);
        partial void OnTerrainChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Piscine
        {
            get
            {
                return _Piscine;
            }
            set
            {
                OnPiscineChanging(value);
                ReportPropertyChanging("Piscine");
                _Piscine = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Piscine");
                OnPiscineChanged();
            }
        }
        private global::System.Boolean _Piscine;
        partial void OnPiscineChanging(global::System.Boolean value);
        partial void OnPiscineChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Terasse
        {
            get
            {
                return _Terasse;
            }
            set
            {
                OnTerasseChanging(value);
                ReportPropertyChanging("Terasse");
                _Terasse = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Terasse");
                OnTerasseChanged();
            }
        }
        private global::System.Boolean _Terasse;
        partial void OnTerasseChanging(global::System.Boolean value);
        partial void OnTerasseChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Chambres
        {
            get
            {
                return _Chambres;
            }
            set
            {
                OnChambresChanging(value);
                ReportPropertyChanging("Chambres");
                _Chambres = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Chambres");
                OnChambresChanged();
            }
        }
        private Nullable<global::System.Int32> _Chambres;
        partial void OnChambresChanging(Nullable<global::System.Int32> value);
        partial void OnChambresChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Pieces
        {
            get
            {
                return _Pieces;
            }
            set
            {
                OnPiecesChanging(value);
                ReportPropertyChanging("Pieces");
                _Pieces = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Pieces");
                OnPiecesChanged();
            }
        }
        private Nullable<global::System.Int32> _Pieces;
        partial void OnPiecesChanging(Nullable<global::System.Int32> value);
        partial void OnPiecesChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Parkings
        {
            get
            {
                return _Parkings;
            }
            set
            {
                OnParkingsChanging(value);
                ReportPropertyChanging("Parkings");
                _Parkings = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Parkings");
                OnParkingsChanged();
            }
        }
        private Nullable<global::System.Int32> _Parkings;
        partial void OnParkingsChanging(Nullable<global::System.Int32> value);
        partial void OnParkingsChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DateStart
        {
            get
            {
                return _DateStart;
            }
            set
            {
                OnDateStartChanging(value);
                ReportPropertyChanging("DateStart");
                _DateStart = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateStart");
                OnDateStartChanged();
            }
        }
        private global::System.DateTime _DateStart;
        partial void OnDateStartChanging(global::System.DateTime value);
        partial void OnDateStartChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DateUpdate
        {
            get
            {
                return _DateUpdate;
            }
            set
            {
                OnDateUpdateChanging(value);
                ReportPropertyChanging("DateUpdate");
                _DateUpdate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateUpdate");
                OnDateUpdateChanged();
            }
        }
        private global::System.DateTime _DateUpdate;
        partial void OnDateUpdateChanging(global::System.DateTime value);
        partial void OnDateUpdateChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Attributes
        {
            get
            {
                return _Attributes;
            }
            set
            {
                OnAttributesChanging(value);
                ReportPropertyChanging("Attributes");
                _Attributes = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Attributes");
                OnAttributesChanged();
            }
        }
        private global::System.String _Attributes;
        partial void OnAttributesChanging(global::System.String value);
        partial void OnAttributesChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Version
        {
            get
            {
                return _Version;
            }
            set
            {
                if (_Version != value)
                {
                    OnVersionChanging(value);
                    ReportPropertyChanging("Version");
                    _Version = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Version");
                    OnVersionChanged();
                }
            }
        }
        private global::System.Int32 _Version;
        partial void OnVersionChanging(global::System.Int32 value);
        partial void OnVersionChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsCurrentVersion
        {
            get
            {
                return _IsCurrentVersion;
            }
            set
            {
                OnIsCurrentVersionChanging(value);
                ReportPropertyChanging("IsCurrentVersion");
                _IsCurrentVersion = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsCurrentVersion");
                OnIsCurrentVersionChanged();
            }
        }
        private global::System.Boolean _IsCurrentVersion;
        partial void OnIsCurrentVersionChanging(global::System.Boolean value);
        partial void OnIsCurrentVersionChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String DPE
        {
            get
            {
                return _DPE;
            }
            set
            {
                OnDPEChanging(value);
                ReportPropertyChanging("DPE");
                _DPE = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("DPE");
                OnDPEChanged();
            }
        }
        private global::System.String _DPE;
        partial void OnDPEChanging(global::System.String value);
        partial void OnDPEChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String GES
        {
            get
            {
                return _GES;
            }
            set
            {
                OnGESChanging(value);
                ReportPropertyChanging("GES");
                _GES = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("GES");
                OnGESChanged();
            }
        }
        private global::System.String _GES;
        partial void OnGESChanging(global::System.String value);
        partial void OnGESChanged();

        #endregion

    
    }

    #endregion

    
}
