//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace ConsoleApplication1.DataAccess
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class ModelSeLogerContainer : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new ModelSeLogerContainer object using the connection string found in the 'ModelSeLogerContainer' section of the application configuration file.
        /// </summary>
        public ModelSeLogerContainer() : base("name=ModelSeLogerContainer", "ModelSeLogerContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ModelSeLogerContainer object.
        /// </summary>
        public ModelSeLogerContainer(string connectionString) : base(connectionString, "ModelSeLogerContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ModelSeLogerContainer object.
        /// </summary>
        public ModelSeLogerContainer(EntityConnection connection) : base(connection, "ModelSeLogerContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Annonce> Annonce
        {
            get
            {
                if ((_Annonce == null))
                {
                    _Annonce = base.CreateObjectSet<Annonce>("Annonce");
                }
                return _Annonce;
            }
        }
        private ObjectSet<Annonce> _Annonce;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Annonce EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToAnnonce(Annonce annonce)
        {
            base.AddObject("Annonce", annonce);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ModelSeLoger", Name="Annonce")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Annonce : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Annonce object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="title">Initial value of the Title property.</param>
        /// <param name="village">Initial value of the Village property.</param>
        /// <param name="piscine">Initial value of the Piscine property.</param>
        /// <param name="terasse">Initial value of the Terasse property.</param>
        public static Annonce CreateAnnonce(global::System.Int32 id, global::System.String title, global::System.String village, global::System.Boolean piscine, global::System.Boolean terasse)
        {
            Annonce annonce = new Annonce();
            annonce.Id = id;
            annonce.Title = title;
            annonce.Village = village;
            annonce.Piscine = piscine;
            annonce.Terasse = terasse;
            return annonce;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Title
        {
            get
            {
                return _Title;
            }
            set
            {
                OnTitleChanging(value);
                ReportPropertyChanging("Title");
                _Title = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Title");
                OnTitleChanged();
            }
        }
        private global::System.String _Title;
        partial void OnTitleChanging(global::System.String value);
        partial void OnTitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Village
        {
            get
            {
                return _Village;
            }
            set
            {
                OnVillageChanging(value);
                ReportPropertyChanging("Village");
                _Village = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Village");
                OnVillageChanged();
            }
        }
        private global::System.String _Village;
        partial void OnVillageChanging(global::System.String value);
        partial void OnVillageChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> Price
        {
            get
            {
                return _Price;
            }
            set
            {
                OnPriceChanging(value);
                ReportPropertyChanging("Price");
                _Price = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Price");
                OnPriceChanged();
            }
        }
        private Nullable<global::System.Double> _Price;
        partial void OnPriceChanging(Nullable<global::System.Double> value);
        partial void OnPriceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ConstuctionYear
        {
            get
            {
                return _ConstuctionYear;
            }
            set
            {
                OnConstuctionYearChanging(value);
                ReportPropertyChanging("ConstuctionYear");
                _ConstuctionYear = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ConstuctionYear");
                OnConstuctionYearChanged();
            }
        }
        private global::System.String _ConstuctionYear;
        partial void OnConstuctionYearChanging(global::System.String value);
        partial void OnConstuctionYearChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Surface
        {
            get
            {
                return _Surface;
            }
            set
            {
                OnSurfaceChanging(value);
                ReportPropertyChanging("Surface");
                _Surface = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Surface");
                OnSurfaceChanged();
            }
        }
        private global::System.String _Surface;
        partial void OnSurfaceChanging(global::System.String value);
        partial void OnSurfaceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Terrain
        {
            get
            {
                return _Terrain;
            }
            set
            {
                OnTerrainChanging(value);
                ReportPropertyChanging("Terrain");
                _Terrain = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Terrain");
                OnTerrainChanged();
            }
        }
        private global::System.String _Terrain;
        partial void OnTerrainChanging(global::System.String value);
        partial void OnTerrainChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Piscine
        {
            get
            {
                return _Piscine;
            }
            set
            {
                OnPiscineChanging(value);
                ReportPropertyChanging("Piscine");
                _Piscine = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Piscine");
                OnPiscineChanged();
            }
        }
        private global::System.Boolean _Piscine;
        partial void OnPiscineChanging(global::System.Boolean value);
        partial void OnPiscineChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Terasse
        {
            get
            {
                return _Terasse;
            }
            set
            {
                OnTerasseChanging(value);
                ReportPropertyChanging("Terasse");
                _Terasse = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Terasse");
                OnTerasseChanged();
            }
        }
        private global::System.Boolean _Terasse;
        partial void OnTerasseChanging(global::System.Boolean value);
        partial void OnTerasseChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Chambres
        {
            get
            {
                return _Chambres;
            }
            set
            {
                OnChambresChanging(value);
                ReportPropertyChanging("Chambres");
                _Chambres = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Chambres");
                OnChambresChanged();
            }
        }
        private global::System.String _Chambres;
        partial void OnChambresChanging(global::System.String value);
        partial void OnChambresChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Pieces
        {
            get
            {
                return _Pieces;
            }
            set
            {
                OnPiecesChanging(value);
                ReportPropertyChanging("Pieces");
                _Pieces = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Pieces");
                OnPiecesChanged();
            }
        }
        private global::System.String _Pieces;
        partial void OnPiecesChanging(global::System.String value);
        partial void OnPiecesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Parkings
        {
            get
            {
                return _Parkings;
            }
            set
            {
                OnParkingsChanging(value);
                ReportPropertyChanging("Parkings");
                _Parkings = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Parkings");
                OnParkingsChanged();
            }
        }
        private global::System.String _Parkings;
        partial void OnParkingsChanging(global::System.String value);
        partial void OnParkingsChanged();

        #endregion

    
    }

    #endregion

    
}
